// ── Per-book mini-game data ───────────────────────────────────────────────────

export interface CrosswordWordDef {
  word: string;
  clue: string;
  emoji: string;
}

export interface UnscrambleWord {
  word: string;
  hint: string;
}

export interface BookGameData {
  wordSearch: {
    title: string;
    wordPool: string[]; // 40+ words — game picks 10 randomly
  };
  crossword: {
    title: string;
    wordPool: CrosswordWordDef[]; // 20 entries — game picks 5 randomly
  };
  findDiff: {
    title: string;
    scene: string;
  };
  hiddenObjects: {
    title: string;
    scene: string;
  };
  memoryMatch: { pairPool: string[] }; // 30+ emojis — game picks 8 randomly
  unscramble: { wordPool: UnscrambleWord[] }; // 30 words — game picks 12
}

export const GAME_DATA: Record<string, BookGameData> = {

  // ── 1. Dream Ideas ──────────────────────────────────────────────────────────
  'dream-ideas': {
    wordSearch: {
      title: 'Find the Dream Words!',
      wordPool: [
        'DREAM','SLEEP','WISH','STARS','MOON','CLOUD','NIGHT','PILLOW','MAGIC','RAINBOW',
        'WONDER','SPARKLE','IMAGINE','FLOAT','COZY','TWILIGHT','DRIFT','GLITTER','FAIRY','WINGS',
        'PEACEFUL','SLEEPY','SNOOZE','GLOW','STARDUST','BLANKET','WHISPER','CASTLE','UNICORN','SHIMMER',
        'SNUGGLE','BEDTIME','FIREFLY','FLUFFY','GENTLE','LULLABY','FANTASY','VOYAGE','MOONBEAM','SWIRL',
        'MERMAID','WISHING','STARLIGHT','DREAMER','TWINKLE',
      ],
    },
    crossword: {
      title: 'Dream Ideas Crossword',
      wordPool: [
        { word: 'WISH',    clue: 'Make one on a shooting star',            emoji: '⭐' },
        { word: 'DREAM',   clue: 'What happens when you close your eyes',   emoji: '💤' },
        { word: 'MOON',    clue: 'Round glow in the night sky',             emoji: '🌙' },
        { word: 'SLEEP',   clue: 'Close your eyes and do this',             emoji: '😴' },
        { word: 'CLOUD',   clue: 'Fluffy white thing in the sky',           emoji: '☁️' },
        { word: 'STAR',    clue: 'Twinkles high above at night',            emoji: '⭐' },
        { word: 'GLOW',    clue: 'Soft shining light in the dark',          emoji: '✨' },
        { word: 'COZY',    clue: 'Warm snuggly feeling in bed',             emoji: '🛏️' },
        { word: 'FAIRY',   clue: 'Tiny magical creature with wings',        emoji: '🧚' },
        { word: 'MAGIC',   clue: 'Something wonderful and impossible',      emoji: '🪄' },
        { word: 'PILLOW',  clue: 'Soft cushion under your head at bedtime', emoji: '🛏️' },
        { word: 'NIGHT',   clue: 'When the stars come out to shine',        emoji: '🌃' },
        { word: 'FLOAT',   clue: 'Drift through the air like a cloud',      emoji: '☁️' },
        { word: 'WONDER',  clue: 'A feeling of amazement and awe',          emoji: '🤩' },
        { word: 'UNICORN', clue: 'A magical horse with a sparkly horn',     emoji: '🦄' },
        { word: 'RAINBOW', clue: 'Colorful arc across the sky',             emoji: '🌈' },
        { word: 'SHIMMER', clue: 'To sparkle and shine softly',             emoji: '✨' },
        { word: 'BLANKET', clue: 'Covers you up warm at bedtime',           emoji: '🛌' },
        { word: 'SPARKLE', clue: 'Twinkle and glitter brightly',            emoji: '🌟' },
        { word: 'SNOOZE',  clue: 'A cozy little nap or sleep',              emoji: '😴' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'dream-ideas' },
    hiddenObjects: { title: 'Find the Hidden Items!', scene: 'dream-ideas' },
    memoryMatch: {
      pairPool: [
        '💭','⭐','🌈','🚀','🦋','🌙','✨','🎨','💤','🌟',
        '🧚','🦄','🌌','☁️','🌠','💫','🌃','🛌','🪄','🎇',
        '🌛','⚡','🌸','🏰','🌺','🎭','🎪','🦉','🕯️','💝',
        '🌊','🐉','🌀','🌻','🌜',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'DREAM',    hint: 'What you have when you sleep' },
        { word: 'STARS',    hint: 'They twinkle in the night sky' },
        { word: 'CLOUD',    hint: 'Fluffy and floats in the sky' },
        { word: 'MAGIC',    hint: 'Something wonderful and surprising' },
        { word: 'SLEEP',    hint: 'Close your eyes and drift away' },
        { word: 'MOON',     hint: 'Round glow in the night sky' },
        { word: 'NIGHT',    hint: 'When the stars come out' },
        { word: 'WISH',     hint: 'Make one on a shooting star' },
        { word: 'FAIRY',    hint: 'Tiny magical creature with wings' },
        { word: 'FLOAT',    hint: 'Drift through the air like a cloud' },
        { word: 'GLOW',     hint: 'Soft light in the dark' },
        { word: 'COZY',     hint: 'Warm and snuggly feeling' },
        { word: 'PILLOW',   hint: 'Soft cushion under your head' },
        { word: 'BLANKET',  hint: 'Covers you up at bedtime' },
        { word: 'UNICORN',  hint: 'Horse with a magical horn' },
        { word: 'RAINBOW',  hint: 'Colorful arc in the sky' },
        { word: 'WONDER',   hint: 'A feeling of amazement' },
        { word: 'SHIMMER',  hint: 'Sparkle and shine softly' },
        { word: 'SNOOZE',   hint: 'Another way to say sleep' },
        { word: 'SPARKLE',  hint: 'Twinkle and glitter brightly' },
        { word: 'GALAXY',   hint: 'Huge collection of stars in space' },
        { word: 'LULLABY',  hint: 'A soft song to help you sleep' },
        { word: 'WHISPER',  hint: 'A very soft quiet voice' },
        { word: 'IMAGINE',  hint: 'Picture something in your mind' },
        { word: 'TWINKLE',  hint: 'The way stars shine in the sky' },
        { word: 'BEDTIME',  hint: 'Time to go to sleep' },
        { word: 'FLUFFY',   hint: 'Soft and light like a cloud' },
        { word: 'FIREFLY',  hint: 'A tiny bug that glows in the dark' },
        { word: 'STARDUST', hint: 'Magical sparkles from stars' },
        { word: 'MERMAID',  hint: 'A magical creature who swims in the sea' },
      ],
    },
  },

  // ── 2. Amber the Dragon Keeper ──────────────────────────────────────────────
  'amber-the-dragon-keeper': {
    wordSearch: {
      title: 'Dragon Cave Words!',
      wordPool: [
        'DRAGON','AMBER','FIRE','CAVE','GEMS','WINGS','MAGIC','ROAR','SCALES','JEWEL',
        'CRYSTAL','TREASURE','GOLD','SMOKE','FLAME','GLITTER','SOAR','HOARD','RUBY','SAPPHIRE',
        'EMERALD','DIAMOND','BOULDER','TUNNEL','SPARKLE','BREATH','KEEPER','CLAW','FANG','TAIL',
        'LAVA','GLOW','ANCIENT','GUARD','BRAVE','FRIEND','SILVER','SHINE','EXPLORE','LEGEND',
        'HERO','PRINCESS','SHADOW','MIGHTY',
      ],
    },
    crossword: {
      title: "Amber's Crossword",
      wordPool: [
        { word: 'FIRE',    clue: 'Dragons breathe this',                    emoji: '🔥' },
        { word: 'CAVE',    clue: 'Where Amber lives underground',            emoji: '🏔️' },
        { word: 'GEMS',    clue: 'Sparkling treasures in the cave',          emoji: '💎' },
        { word: 'ROAR',    clue: 'Loud sound a dragon makes',                emoji: '🦁' },
        { word: 'WING',    clue: 'Dragons use these to fly',                 emoji: '🦅' },
        { word: 'GOLD',    clue: 'Shiny yellow treasure metal',              emoji: '🥇' },
        { word: 'RUBY',    clue: 'A bright red gemstone',                    emoji: '💎' },
        { word: 'CLAW',    clue: "Sharp curved nail on a dragon's foot",     emoji: '🐾' },
        { word: 'SMOKE',   clue: 'Rises up when something burns',            emoji: '💨' },
        { word: 'FLAME',   clue: 'The bright glowing part of a fire',        emoji: '🔥' },
        { word: 'SCALES',  clue: 'Armor-like skin covering a dragon',        emoji: '🐉' },
        { word: 'SOAR',    clue: 'To fly high up in the sky',                emoji: '🦅' },
        { word: 'HOARD',   clue: 'A big pile of treasure',                   emoji: '💰' },
        { word: 'BRAVE',   clue: 'Not afraid of anything',                   emoji: '🦁' },
        { word: 'KEEPER',  clue: 'Someone who takes care of something',      emoji: '🧑' },
        { word: 'CRYSTAL', clue: 'A clear sparkly rock',                     emoji: '💎' },
        { word: 'JEWEL',   clue: 'A precious sparkling stone',               emoji: '��' },
        { word: 'LAVA',    clue: 'Hot melted rock from a volcano',           emoji: '🌋' },
        { word: 'LEGEND',  clue: 'A famous story passed down through time',  emoji: '📖' },
        { word: 'EMERALD', clue: 'A beautiful green gemstone',               emoji: '💚' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'amber' },
    hiddenObjects: { title: 'Find the Hidden Gems!', scene: 'amber' },
    memoryMatch: {
      pairPool: [
        '🐉','🔥','💎','🏰','🌋','⚔️','��','👑','🪨','🌟',
        '🦅','💰','🏺','⚡','🐾','🌈','🌙','🧝','💜','🔮',
        '🗡️','🦁','🌿','🗺️','🔑','🏆','🛡️','✨','📜','🌊',
        '🎇','💫','🫙','🌺','🦄',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'DRAGON',   hint: 'A fire-breathing flying creature' },
        { word: 'AMBER',    hint: "The dragon keeper's name" },
        { word: 'FIRE',     hint: 'Dragons breathe this' },
        { word: 'CAVE',     hint: 'Where Amber lives underground' },
        { word: 'WINGS',    hint: 'Dragons use these to fly' },
        { word: 'GEMS',     hint: 'Sparkling treasures in the cave' },
        { word: 'ROAR',     hint: 'Loud sound a dragon makes' },
        { word: 'GOLD',     hint: 'Shiny yellow treasure metal' },
        { word: 'RUBY',     hint: 'A bright red gemstone' },
        { word: 'CLAW',     hint: "Sharp nail on a dragon's foot" },
        { word: 'SMOKE',    hint: 'Rises up when something burns' },
        { word: 'FLAME',    hint: 'The bright glowing part of a fire' },
        { word: 'SCALES',   hint: 'Armor-like skin covering a dragon' },
        { word: 'SOAR',     hint: 'Fly high up in the sky' },
        { word: 'HOARD',    hint: 'A big pile of treasure' },
        { word: 'BRAVE',    hint: 'Not afraid of anything' },
        { word: 'KEEPER',   hint: 'Someone who takes care of something' },
        { word: 'CRYSTAL',  hint: 'A clear sparkly rock' },
        { word: 'JEWEL',    hint: 'A precious sparkling stone' },
        { word: 'LAVA',     hint: 'Hot melted rock from a volcano' },
        { word: 'LEGEND',   hint: 'A famous story passed down through time' },
        { word: 'SILVER',   hint: 'A shiny grey precious metal' },
        { word: 'EMERALD',  hint: 'A beautiful green gemstone' },
        { word: 'DIAMOND',  hint: 'The sparkliest gemstone of all' },
        { word: 'TREASURE', hint: 'A collection of precious things' },
        { word: 'ANCIENT',  hint: 'Very very old' },
        { word: 'EXPLORE',  hint: 'Go on an adventure to discover new things' },
        { word: 'PRINCESS', hint: 'A royal girl in a story' },
        { word: 'SAPPHIRE', hint: 'A beautiful blue gemstone' },
        { word: 'SHADOW',   hint: 'A dark shape that follows you' },
      ],
    },
  },

  // ── 3. What's Your Poo Poo Face ─────────────────────────────────────────────
  'whats-your-poo-poo-face': {
    wordSearch: {
      title: 'Silly Poo Poo Words!',
      wordPool: [
        'GIGGLE','FUNNY','STINKY','LAUGH','SILLY','FACE','TUMMY','NOSE','WIGGLE','GRIN',
        'SMELLY','SQUISH','BLECH','YUCKY','BURP','TOOT','BELLY','CHEEKS','MOUTH','TONGUE',
        'SMILE','SNORT','CHORTLE','DIZZY','WACKY','GROSS','HICCUP','BLOOP','SNIFF','POKE',
        'JIGGLE','TICKLE','BOUNCE','HOWL','SQUEAL','SHAKE','OOPS','SPUTTER','BOING','SNICKER',
        'CACKLE','HOOT','WOBBLY',
      ],
    },
    crossword: {
      title: 'Poo Poo Crossword',
      wordPool: [
        { word: 'FACE',    clue: "It's on the front of your head",           emoji: '😄' },
        { word: 'FUNNY',   clue: 'Something that makes you laugh',           emoji: '😂' },
        { word: 'NOSE',    clue: 'It smells things — especially stinky ones',emoji: '👃' },
        { word: 'LAUGH',   clue: 'What you do when things are silly',        emoji: '🤣' },
        { word: 'TUMMY',   clue: 'Your belly — your squishiest part',        emoji: '🤰' },
        { word: 'GIGGLE',  clue: 'A little baby laugh',                      emoji: '😆' },
        { word: 'SILLY',   clue: 'Goofy and funny and not serious at all',   emoji: '🤪' },
        { word: 'WIGGLE',  clue: 'Move from side to side',                   emoji: '💃' },
        { word: 'GRIN',    clue: 'A big wide smile',                         emoji: '😁' },
        { word: 'BURP',    clue: 'A loud sound from your tummy',             emoji: '😮' },
        { word: 'TOOT',    clue: 'A funny sound from your bottom',           emoji: '💨' },
        { word: 'BELLY',   clue: 'Another word for your tummy',              emoji: '🍑' },
        { word: 'CHEEKS',  clue: 'Soft parts on the sides of your face',     emoji: '😊' },
        { word: 'MOUTH',   clue: 'You eat and talk with this',               emoji: '👄' },
        { word: 'TONGUE',  clue: 'Wiggly pink thing inside your mouth',      emoji: '👅' },
        { word: 'SNORT',   clue: 'A funny laugh through your nose',          emoji: '🐷' },
        { word: 'TICKLE',  clue: 'Touch lightly to make someone giggle',     emoji: '🤭' },
        { word: 'HICCUP',  clue: 'A funny jump in your tummy',               emoji: '😮' },
        { word: 'SNIFF',   clue: 'What your nose does to smell things',      emoji: '👃' },
        { word: 'BOUNCE',  clue: 'Jump up and down like a bouncy ball',      emoji: '⚽' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'poo-poo-face' },
    hiddenObjects: { title: 'Find the Hidden Things!', scene: 'poo-poo-face' },
    memoryMatch: {
      pairPool: [
        '💩','😂','🚽','🧻','😆','🤣','🪠','😜','🤪','😝',
        '👃','👅','💨','🐷','😁','🙃','🤭','😹','🫢','🥴',
        '😵','🤡','🎭','🌀','💦','🫧','🧼','🛁','🤸','🐸',
        '🎪','🎠','🌈','🎡','🎢',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'SILLY',   hint: 'Makes you giggle and laugh' },
        { word: 'FUNNY',   hint: 'Ha ha ha!' },
        { word: 'LAUGH',   hint: 'What you do when something is silly' },
        { word: 'TUMMY',   hint: 'Your belly your middle' },
        { word: 'STINKY',  hint: 'Not a nice smell!' },
        { word: 'GIGGLE',  hint: 'A little baby laugh' },
        { word: 'WIGGLE',  hint: 'Move from side to side' },
        { word: 'GRIN',    hint: 'A big wide smile' },
        { word: 'BURP',    hint: 'A loud sound from your tummy' },
        { word: 'TOOT',    hint: 'A funny sound from your bottom' },
        { word: 'BELLY',   hint: 'Another word for your tummy' },
        { word: 'CHEEKS',  hint: 'Soft parts on the sides of your face' },
        { word: 'MOUTH',   hint: 'You eat and talk with this' },
        { word: 'TONGUE',  hint: 'Wiggly pink thing inside your mouth' },
        { word: 'SNORT',   hint: 'A funny laugh through your nose' },
        { word: 'TICKLE',  hint: 'Touch lightly to make someone giggle' },
        { word: 'HICCUP',  hint: 'A funny jump in your tummy' },
        { word: 'SNIFF',   hint: 'What your nose does to smell things' },
        { word: 'BOUNCE',  hint: 'Jump up and down like a bouncy ball' },
        { word: 'DIZZY',   hint: 'Spinning around until you fall over' },
        { word: 'WACKY',   hint: 'Really really silly and strange' },
        { word: 'SQUISH',  hint: 'Press something soft and smushy' },
        { word: 'JIGGLE',  hint: 'Shake and wobble like jelly' },
        { word: 'SNICKER', hint: 'A sneaky little laugh' },
        { word: 'CACKLE',  hint: 'A loud wild laugh' },
        { word: 'CHORTLE', hint: 'A happy chuckling laugh' },
        { word: 'SPUTTER', hint: 'Make funny spit noises' },
        { word: 'WOBBLY',  hint: 'Shaky and not steady' },
        { word: 'BOING',   hint: 'The sound of bouncing' },
        { word: 'OOPS',    hint: 'What you say when something goes wrong' },
      ],
    },
  },

  // ── 4. Gilroy's Gobble ───────────────────────────────────────────────────────
  'gilroys-gobble': {
    wordSearch: {
      title: 'Gobble Gobble Words!',
      wordPool: [
        'GOBBLE','TURKEY','BARN','FARM','WINGS','CLUCK','VOICE','NEST','FLOCK','PRIDE',
        'BEAK','FEATHERS','STRUT','WATTLE','PREEN','FOWL','ROOST','HAYSTACK','SILO','TRACTOR',
        'HARVEST','CORN','STRAW','FENCE','MUDDY','HORSES','CHICKENS','ROOSTER','GRAINS','SEEDS',
        'FIELD','MEADOW','COUNTRY','GOBBLER','HEN','CHICK','HATCH','EGGS','QUACK','MOO',
        'OINK','NEIGH','TROUGH','PASTURE',
      ],
    },
    crossword: {
      title: "Gilroy's Crossword",
      wordPool: [
        { word: 'BARN',     clue: 'The big red building on a farm',             emoji: '🏚️' },
        { word: 'BEAK',     clue: 'A bird uses this to eat',                    emoji: '🦅' },
        { word: 'WING',     clue: 'Birds use these to fly',                     emoji: '🪶' },
        { word: 'HENS',     clue: 'Female chickens on the farm',                emoji: '🐔' },
        { word: 'NEST',     clue: 'Where a bird lays its eggs',                 emoji: '🪺' },
        { word: 'CLUCK',    clue: 'The sound a chicken makes',                  emoji: '🐔' },
        { word: 'STRUT',    clue: 'Walk proudly like a turkey',                 emoji: '🦃' },
        { word: 'FLOCK',    clue: 'A group of birds together',                  emoji: '🐦' },
        { word: 'CORN',     clue: 'Yellow vegetable grown on a farm',           emoji: '🌽' },
        { word: 'STRAW',    clue: 'Dry yellow stalks on the barn floor',        emoji: '🌾' },
        { word: 'ROOST',    clue: 'Where chickens sleep at night',              emoji: '🐓' },
        { word: 'EGGS',     clue: 'Round things a hen lays',                    emoji: '🥚' },
        { word: 'SILO',     clue: 'Tall round tower on a farm for grain',       emoji: '🏗️' },
        { word: 'FEATHERS', clue: "Soft coverings on a bird's body",            emoji: '🪶' },
        { word: 'CHICK',    clue: 'A baby chicken',                             emoji: '🐥' },
        { word: 'HARVEST',  clue: 'When farmers pick all the crops',            emoji: '🌾' },
        { word: 'GOBBLE',   clue: 'The sound Gilroy the turkey makes',          emoji: '🦃' },
        { word: 'PREEN',    clue: 'When a bird cleans its feathers',            emoji: '🦢' },
        { word: 'WATTLE',   clue: "The red wobbly thing under a turkey's chin", emoji: '🦃' },
        { word: 'ROOSTER',  clue: 'The boy chicken who crows at sunrise',       emoji: '🐓' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'gilroy' },
    hiddenObjects: { title: 'Find the Farm Things!', scene: 'gilroy' },
    memoryMatch: {
      pairPool: [
        '🦃','🏚️','🌽','🐓','🌾','🥚','🐔','🍂','🐷','🐄',
        '🐎','🐑','🐐','🦆','🪺','🌻','🌿','🍁','��','🚜',
        '🌳','🐝','🦋','🌼','🌱','🎃','🥕','🍎','🍇','🌰',
        '🐇','🌤️','🌈','🫙','🏕️',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'TURKEY',   hint: 'The big bird on the farm' },
        { word: 'GOBBLE',   hint: 'Sound a turkey makes' },
        { word: 'BARN',     hint: 'Big red building on a farm' },
        { word: 'WINGS',    hint: 'Birds use these to fly' },
        { word: 'NEST',     hint: 'Where birds lay eggs' },
        { word: 'CLUCK',    hint: 'Sound a chicken makes' },
        { word: 'STRUT',    hint: 'Walk proudly like a turkey' },
        { word: 'FLOCK',    hint: 'A group of birds together' },
        { word: 'CORN',     hint: 'Yellow vegetable on the farm' },
        { word: 'STRAW',    hint: 'Dry yellow stalks in the barn' },
        { word: 'ROOST',    hint: 'Where chickens sleep at night' },
        { word: 'FEATHERS', hint: "Soft coverings on a bird's body" },
        { word: 'CHICK',    hint: 'A baby chicken' },
        { word: 'HARVEST',  hint: 'When farmers pick all the crops' },
        { word: 'PREEN',    hint: "When a bird cleans its feathers" },
        { word: 'WATTLE',   hint: "The red wobbly bit under a turkey's chin" },
        { word: 'ROOSTER',  hint: 'The boy chicken who crows at sunrise' },
        { word: 'SILO',     hint: 'Tall round tower on a farm for grain' },
        { word: 'BEAK',     hint: 'A bird uses this to eat' },
        { word: 'HATCH',    hint: 'When a baby chick breaks out of its egg' },
        { word: 'HAYSTACK', hint: 'A big pile of dried hay' },
        { word: 'TRACTOR',  hint: 'The big machine that helps on the farm' },
        { word: 'MEADOW',   hint: 'A green field full of grass and flowers' },
        { word: 'HORSES',   hint: 'Big animals on the farm that you can ride' },
        { word: 'GRAINS',   hint: 'Tiny seeds like wheat or corn' },
        { word: 'FIELD',    hint: 'A large open space for growing crops' },
        { word: 'SEEDS',    hint: 'Tiny things that grow into plants' },
        { word: 'OINK',     hint: 'Sound a pig makes' },
        { word: 'NEIGH',    hint: 'Sound a horse makes' },
        { word: 'QUACK',    hint: 'Sound a duck makes' },
      ],
    },
  },

  // ── 5. Finding Hampton ───────────────────────────────────────────────────────
  'finding-hampton': {
    wordSearch: {
      title: "Find Hampton's Words!",
      wordPool: [
        'HIPPO','RHINO','GIFT','PARTY','SHARE','CAKE','FRIENDS','LAUGH','SMILE','BALLOON',
        'CANDLES','BIRTHDAY','RIBBON','WRAPPER','SURPRISE','SEARCH','WANDER','EXPLORE','HAPPY','JOY',
        'PRESENTS','COLORFUL','BOUNCE','CLAP','CHEER','SING','DANCE','SWEET','FROSTING','STREAMERS',
        'CONFETTI','TOGETHER','FOUND','LOST','WISHING','INVITE','HAMPTON','CELEBRATE','SQUEAL','CUPCAKE',
        'GRATEFUL','KINDNESS','SPRINKLES',
      ],
    },
    crossword: {
      title: "Hampton's Crossword",
      wordPool: [
        { word: 'HIPPO',    clue: "Hampton's animal — big, round, and loveable", emoji: '🦛' },
        { word: 'GIFT',     clue: 'Something wrapped in a bow for a friend',     emoji: '🎁' },
        { word: 'CAKE',     clue: 'Sweet birthday treat with candles',           emoji: '🎂' },
        { word: 'PARTY',    clue: 'Celebration with balloons and friends',       emoji: '🎉' },
        { word: 'SHARE',    clue: 'Give some to your friends too',               emoji: '🤝' },
        { word: 'SMILE',    clue: 'Happy curved shape on your face',             emoji: '😊' },
        { word: 'BALLOON',  clue: 'Round colorful floating decoration',          emoji: '🎈' },
        { word: 'RIBBON',   clue: 'Tied in a bow on top of a present',           emoji: '🎀' },
        { word: 'SEARCH',   clue: 'Look everywhere to find something',           emoji: '🔍' },
        { word: 'HAPPY',    clue: 'The feeling when it is your birthday',        emoji: '😄' },
        { word: 'JOY',      clue: 'A big wonderful happy feeling',               emoji: '🌟' },
        { word: 'FRIENDS',  clue: 'People you love to play with',               emoji: '👫' },
        { word: 'FOUND',    clue: 'When you stop being lost',                    emoji: '✅' },
        { word: 'CHEER',    clue: 'Shout hooray and clap your hands',           emoji: '🎉' },
        { word: 'CANDLES',  clue: 'Blow these out on your birthday cake',        emoji: '🕯️' },
        { word: 'CONFETTI', clue: 'Tiny colorful paper pieces at a party',       emoji: '🎊' },
        { word: 'FROSTING', clue: 'Sweet creamy topping on a cake',             emoji: '🎂' },
        { word: 'SURPRISE', clue: "Something you didn't expect at all",         emoji: '😲' },
        { word: 'BIRTHDAY', clue: 'The day you were born — time to celebrate!', emoji: '🎂' },
        { word: 'CUPCAKE',  clue: 'A tiny little cake just for you',            emoji: '🧁' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'hampton' },
    hiddenObjects: { title: "Find Hampton's Things!", scene: 'hampton' },
    memoryMatch: {
      pairPool: [
        '🦛','🎁','🎂','🎉','💝','🎈','🎀','🌟','🧁','🕯️',
        '🎊','🎏','🎗️','🫶','🤝','🌈','😊','💜','🌸','🌻',
        '🎵','🎶','🧸','🪀','🎠','🎡','🎪','⭐','🫂','🥳',
        '🌺','🎇','🫙','🏆','🌼',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'HIPPO',     hint: "Hampton's big loveable animal" },
        { word: 'PARTY',     hint: 'Celebration with balloons and cake' },
        { word: 'GIFT',      hint: 'Something wrapped with a bow' },
        { word: 'CAKE',      hint: 'Sweet birthday treat' },
        { word: 'SMILE',     hint: 'Happy face expression' },
        { word: 'SHARE',     hint: 'Give some to your friends too' },
        { word: 'BALLOON',   hint: 'Round colorful floating decoration' },
        { word: 'RIBBON',    hint: 'Tied in a bow on a present' },
        { word: 'HAPPY',     hint: 'The feeling on your birthday' },
        { word: 'FOUND',     hint: 'When you stop being lost' },
        { word: 'CHEER',     hint: 'Shout hooray and clap' },
        { word: 'CANDLES',   hint: 'Blow these out on your cake' },
        { word: 'CONFETTI',  hint: 'Tiny colorful paper at a party' },
        { word: 'FROSTING',  hint: 'Sweet creamy topping on a cake' },
        { word: 'SURPRISE',  hint: "Something you didn't expect" },
        { word: 'BIRTHDAY',  hint: 'The day you were born' },
        { word: 'CUPCAKE',   hint: 'A tiny little cake just for you' },
        { word: 'FRIENDS',   hint: 'People you love to play with' },
        { word: 'BOUNCE',    hint: 'Jump up and down with excitement' },
        { word: 'DANCE',     hint: 'Move your body to music at a party' },
        { word: 'EXPLORE',   hint: 'Go looking around for something' },
        { word: 'WANDER',    hint: 'Walk around looking for something' },
        { word: 'SEARCH',    hint: 'Look everywhere to find something' },
        { word: 'WISHING',   hint: 'Hoping for something special' },
        { word: 'STREAMERS', hint: 'Long colorful ribbons at a party' },
        { word: 'TOGETHER',  hint: 'Everyone at the same place' },
        { word: 'CELEBRATE', hint: 'Have a party for something special' },
        { word: 'PRESENTS',  hint: 'Wrapped gifts at a birthday party' },
        { word: 'GRATEFUL',  hint: 'Feeling thankful for something nice' },
        { word: 'KINDNESS',  hint: 'Being nice and caring to others' },
      ],
    },
  },

  // ── 6. The Lumpiest Pumpkin ──────────────────────────────────────────────────
  'the-lumpiest-pumpkin': {
    wordSearch: {
      title: 'Pumpkin Patch Words!',
      wordPool: [
        'PUMPKIN','LUMPY','PATCH','SEEDS','ORANGE','CARVE','LANTERN','SPOOKY','STEM','GLOW',
        'BUMPY','WOBBLY','ROUND','HOLLOW','AUTUMN','HARVEST','SCARECROW','COBWEB','BATS','GHOST',
        'WITCH','CAULDRON','BROOMSTICK','LEAVES','ACORN','PINECONE','COSTUME','TRICK','TREAT','CANDY',
        'CREEPY','EERIE','SHADOW','CANDLE','MOONLIT','PORCH','CIDER','CRINKLE','SQUASH','GOURD',
        'FALLEN','HAYBALE','LANTERNS',
      ],
    },
    crossword: {
      title: 'Pumpkin Crossword',
      wordPool: [
        { word: 'STEM',     clue: 'The green stalk on top of a pumpkin',              emoji: '🌿' },
        { word: 'SEEDS',    clue: 'Slimy insides of a carved pumpkin',                emoji: '🌰' },
        { word: 'GLOW',     clue: 'What a jack-o-lantern does in the dark',           emoji: '🕯️' },
        { word: 'LUMPY',    clue: 'Not smooth — bumpy and wobbly',                    emoji: '😄' },
        { word: 'PATCH',    clue: 'A field full of pumpkins',                         emoji: '🎃' },
        { word: 'CARVE',    clue: 'Cut a face into a pumpkin',                        emoji: '🔪' },
        { word: 'GHOST',    clue: 'A spooky floating spirit',                         emoji: '👻' },
        { word: 'WITCH',    clue: 'Rides a broomstick on Halloween',                  emoji: '🧙' },
        { word: 'BATS',     clue: 'Winged creatures that fly at night',               emoji: '🦇' },
        { word: 'CANDY',    clue: 'Sweet treats you get on Halloween',                emoji: '🍬' },
        { word: 'TRICK',    clue: "What you say before 'treat'",                      emoji: '🎃' },
        { word: 'TREAT',    clue: 'What you get when you knock on doors',             emoji: '🍭' },
        { word: 'CREEPY',   clue: 'Spooky and a little scary',                        emoji: '😱' },
        { word: 'COBWEB',   clue: 'Sticky spider creation in a spooky place',         emoji: '🕸️' },
        { word: 'ACORN',    clue: 'A tiny round nut from an oak tree',                emoji: '🌰' },
        { word: 'AUTUMN',   clue: 'The season when leaves turn orange',               emoji: '🍂' },
        { word: 'HOLLOW',   clue: 'Empty inside like a carved pumpkin',               emoji: '🎃' },
        { word: 'HARVEST',  clue: 'Picking all the crops in autumn',                  emoji: '🌾' },
        { word: 'COSTUME',  clue: 'Dress-up clothes for Halloween',                   emoji: '👗' },
        { word: 'LANTERN',  clue: 'A glowing light inside a carved pumpkin',          emoji: '🎃' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'lumpiest-pumpkin' },
    hiddenObjects: { title: 'Find the Patch Things!', scene: 'lumpiest-pumpkin' },
    memoryMatch: {
      pairPool: [
        '🎃','🍂','🌾','👻','🕯️','🌙','⭐','🍁','🦇','🕷️',
        '🕸️','🧙','🌕','🏚️','🍬','🍭','🌰','🐺','🦉','🌿',
        '🐸','🌑','🎭','😱','🌫️','💀','🔮','🌛','⚰️','🧟',
        '🦝','🎇','🌜','🌃','🌠',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'PUMPKIN',    hint: 'Orange and round great for Halloween' },
        { word: 'LUMPY',      hint: 'Not smooth bumpy and wobbly' },
        { word: 'SEEDS',      hint: 'Slimy insides of a carved pumpkin' },
        { word: 'GLOW',       hint: 'What a jack-o-lantern does in the dark' },
        { word: 'PATCH',      hint: 'A field full of pumpkins' },
        { word: 'CARVE',      hint: 'Cut a face into a pumpkin' },
        { word: 'GHOST',      hint: 'A spooky floating spirit' },
        { word: 'WITCH',      hint: 'Rides a broomstick on Halloween' },
        { word: 'CANDY',      hint: 'Sweet treats you get on Halloween' },
        { word: 'CREEPY',     hint: 'Spooky and a little scary' },
        { word: 'COBWEB',     hint: 'Sticky spider creation in a spooky house' },
        { word: 'ACORN',      hint: 'A tiny round nut from an oak tree' },
        { word: 'AUTUMN',     hint: 'The season when leaves turn orange and red' },
        { word: 'HOLLOW',     hint: 'Empty inside like a carved pumpkin' },
        { word: 'HARVEST',    hint: 'Picking all the crops in autumn' },
        { word: 'COSTUME',    hint: 'Dress-up clothes for Halloween' },
        { word: 'LANTERN',    hint: 'A glowing light inside a carved pumpkin' },
        { word: 'SCARECROW',  hint: 'A straw figure in the field to scare birds' },
        { word: 'CAULDRON',   hint: 'A big pot used by witches' },
        { word: 'PINECONE',   hint: 'A prickly seed case from a pine tree' },
        { word: 'ORANGE',     hint: 'The color of a pumpkin' },
        { word: 'SHADOW',     hint: 'A dark shape you see when light shines on you' },
        { word: 'EERIE',      hint: 'Strange and spooky' },
        { word: 'TRICK',      hint: "What you say before 'treat'" },
        { word: 'TREAT',      hint: 'Sweet things you get on Halloween' },
        { word: 'GOURD',      hint: 'A cousin of the pumpkin' },
        { word: 'SQUASH',     hint: 'A vegetable like a pumpkin' },
        { word: 'MOONLIT',    hint: 'Lit up by the glow of the moon' },
        { word: 'WOBBLY',     hint: 'Shaky and unsteady' },
        { word: 'BROOMSTICK', hint: 'What witches fly on' },
      ],
    },
  },

  // ── 7. One Tom Turkey ────────────────────────────────────────────────────────
  'one-tom-turkey': {
    wordSearch: {
      title: 'Thanksgiving Words!',
      wordPool: [
        'TURKEY','FEAST','GRAVY','CORN','PIE','STUFFED','TABLE','THANKFUL','FAMILY','PARADE',
        'CRANBERRY','PILGRIMS','HARVEST','AUTUMN','GRATEFUL','DRUMSTICK','BLESSING','GATHER','SHARE','BOUNTY',
        'DINNER','YAMS','SQUASH','BREAD','BUTTER','STUFFING','WISHBONE','MASHED','POTATOES','COUSINS',
        'PLATTER','CANDLES','NAPKINS','PUMPKIN','CIDER','FOOTBALL','GOBBLE','SPOON','FORKS','PLATES',
        'APPLES','PILGRIM','CORNBREAD',
      ],
    },
    crossword: {
      title: "Tom Turkey's Crossword",
      wordPool: [
        { word: 'FEAST',    clue: 'A HUGE delicious meal with everyone you love',  emoji: '🍽️' },
        { word: 'CORN',     clue: 'Yellow vegetable on the cob',                   emoji: '🌽' },
        { word: 'PIE',      clue: 'Sweet round dessert — pumpkin flavor!',         emoji: '🥧' },
        { word: 'TABLE',    clue: 'Where everyone sits for Thanksgiving dinner',   emoji: '🪑' },
        { word: 'GRAVY',    clue: 'Thick brown sauce poured on everything',        emoji: '🍲' },
        { word: 'FAMILY',   clue: 'The people you love most all together',         emoji: '👨‍👩‍👧‍👦' },
        { word: 'GATHER',   clue: 'Come together in one place',                    emoji: '🫂' },
        { word: 'HARVEST',  clue: 'Picking all the food from the fields',          emoji: '🌾' },
        { word: 'PARADE',   clue: 'Floats and marching bands down the street',     emoji: '🎺' },
        { word: 'YAMS',     clue: 'Orange sweet potato — delicious at Thanksgiving',emoji: '🍠' },
        { word: 'BREAD',    clue: 'Warm rolls on the Thanksgiving table',          emoji: '🍞' },
        { word: 'GOBBLE',   clue: 'What Tom Turkey says',                          emoji: '🦃' },
        { word: 'PILGRIMS', clue: 'People who sailed to America long ago',         emoji: '⛵' },
        { word: 'GRATEFUL', clue: 'Feeling thankful for good things in life',      emoji: '🙏' },
        { word: 'AUTUMN',   clue: 'The season of Thanksgiving and falling leaves', emoji: '🍂' },
        { word: 'STUFFING', clue: 'Yummy bread mixture inside the turkey',         emoji: '🫓' },
        { word: 'WISHBONE', clue: 'A special bone you pull to make a wish',        emoji: '🦴' },
        { word: 'STUFFED',  clue: 'Very full from eating too much turkey',         emoji: '😋' },
        { word: 'BOUNTY',   clue: 'A wonderful big supply of food and good things',emoji: '🌽' },
        { word: 'CIDER',    clue: 'A sweet apple drink at harvest time',           emoji: '🍎' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'one-tom-turkey' },
    hiddenObjects: { title: 'Find the Feast Things!', scene: 'one-tom-turkey' },
    memoryMatch: {
      pairPool: [
        '🦃','🍗','🌽','🥧','🍽️','🙏','🍎','🥕','🍞','🧈',
        '🍠','🫐','🌾','🎺','⛵','🍂','🕯️','🫂','🏡','🌻',
        '🍇','🥗','🍲','🫓','🌰','🍁','🦴','🎉','🌿','🍓',
        '🎊','🌈','🫙','🏆','🌼',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'TURKEY',    hint: 'The main dish on Thanksgiving' },
        { word: 'FEAST',     hint: 'A huge delicious meal' },
        { word: 'CORN',      hint: 'Yellow vegetable on the cob' },
        { word: 'GRAVY',     hint: 'Thick brown sauce on everything' },
        { word: 'FAMILY',    hint: 'The people you love most' },
        { word: 'PARADE',    hint: 'Floats and bands down the street' },
        { word: 'HARVEST',   hint: 'Picking food from the fields' },
        { word: 'GATHER',    hint: 'Come together in one place' },
        { word: 'GOBBLE',    hint: 'What Tom Turkey says' },
        { word: 'BREAD',     hint: 'Warm rolls on the table' },
        { word: 'YAMS',      hint: 'Orange sweet potato' },
        { word: 'GRATEFUL',  hint: 'Feeling thankful for good things' },
        { word: 'AUTUMN',    hint: 'The season of Thanksgiving' },
        { word: 'STUFFING',  hint: 'Yummy bread mixture inside the turkey' },
        { word: 'WISHBONE',  hint: 'A special bone you pull to make a wish' },
        { word: 'PILGRIMS',  hint: 'People who sailed to America long ago' },
        { word: 'STUFFED',   hint: 'Full from eating too much' },
        { word: 'THANKFUL',  hint: 'Feeling glad about something good' },
        { word: 'BOUNTY',    hint: 'A wonderful big supply of food' },
        { word: 'POTATOES',  hint: 'Mashed and served with gravy' },
        { word: 'COUSINS',   hint: 'Your aunts and uncles children' },
        { word: 'BLESSING',  hint: 'A prayer of thanks before the meal' },
        { word: 'PUMPKIN',   hint: 'The flavor of Thanksgiving pie' },
        { word: 'PLATTER',   hint: 'A big plate for serving food' },
        { word: 'CANDLES',   hint: 'Lit on the Thanksgiving table' },
        { word: 'DINNER',    hint: 'The big meal of the day' },
        { word: 'FOOTBALL',  hint: 'A game people play on Thanksgiving' },
        { word: 'CIDER',     hint: 'A sweet apple drink at harvest time' },
        { word: 'CRANBERRY', hint: 'Tart red sauce at Thanksgiving dinner' },
        { word: 'DRUMSTICK', hint: 'A big turkey leg to eat' },
      ],
    },
  },

  // ── 8. Ollie Come Home ───────────────────────────────────────────────────────
  'ollie-come-home': {
    wordSearch: {
      title: "Find Ollie's Words!",
      wordPool: [
        'OLLIE','MEOW','HOME','COZY','LOST','PAWS','FUZZY','PURR','WARM','KITTEN',
        'CUDDLE','SOFT','SNUGGLE','WHISKERS','NUZZLE','RESCUE','MISSING','WANDER','SEARCH','RETURN',
        'COMFORT','SAFE','BELONG','LOVE','CURLED','PLAYFUL','YARN','CATNIP','PROWL','TABBY',
        'STRIPED','FLUFFY','VELVET','GENTLE','HAPPY','SHELTER','INDOOR','WINDOW','SUNBEAM','BASKET',
        'PADDING','BOUNCY','STRETCHY','PURRING',
      ],
    },
    crossword: {
      title: "Ollie's Crossword",
      wordPool: [
        { word: 'MEOW',     clue: 'The sound a cat makes',                         emoji: '🐱' },
        { word: 'HOME',     clue: 'Where Ollie really wants to be',                emoji: '🏡' },
        { word: 'PAWS',     clue: "A cat's fluffy feet",                           emoji: '🐾' },
        { word: 'COZY',     clue: 'Warm, soft, snuggly feeling',                   emoji: '🛋️' },
        { word: 'PURR',     clue: 'Happy rumbling sound cats make',                emoji: '😻' },
        { word: 'LOST',     clue: "When you can't find your way back home",        emoji: '😢' },
        { word: 'FUZZY',    clue: 'Covered in soft fluffy fur',                    emoji: '🐱' },
        { word: 'WARM',     clue: 'Comfortable and not cold at all',               emoji: '☀️' },
        { word: 'KITTEN',   clue: 'A baby cat',                                    emoji: '🐈' },
        { word: 'CUDDLE',   clue: 'Hold someone close and snuggle up',             emoji: '🤗' },
        { word: 'RESCUE',   clue: 'Save someone who is in trouble',                emoji: '🦸' },
        { word: 'WHISKERS', clue: "Long stiff hairs on a cat's face",              emoji: '😺' },
        { word: 'NUZZLE',   clue: 'Rub your nose against something warm and soft', emoji: '💕' },
        { word: 'SAFE',     clue: 'Protected and not in danger',                   emoji: '🏠' },
        { word: 'BELONG',   clue: 'Be in the right place with the right people',   emoji: '💜' },
        { word: 'RETURN',   clue: 'Come back to where you started',                emoji: '🔄' },
        { word: 'COMFORT',  clue: 'Make someone feel better and less scared',      emoji: '🤗' },
        { word: 'SUNBEAM',  clue: 'A warm stripe of sunlight from a window',       emoji: '☀️' },
        { word: 'CATNIP',   clue: 'A plant that cats go crazy for',                emoji: '🌿' },
        { word: 'PROWL',    clue: 'Walk quietly and carefully like a cat hunting', emoji: '🐱' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'ollie' },
    hiddenObjects: { title: "Find Ollie's Things!", scene: 'ollie' },
    memoryMatch: {
      pairPool: [
        '🐱','🏡','🐾','❤️','🌳','🛋️','😻','🎀','🧶','🌿',
        '☀️','🐈','🪟','🛏️','🍃','🌸','🫧','🪑','🌻','💜',
        '🌈','🎁','🤗','⭐','🌙','🫂','🧸','🐟','🍎','🌊',
        '🏠','🔔','🌺','🌼','🎶',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'KITTEN',   hint: 'A baby cat' },
        { word: 'MEOW',     hint: 'Sound a cat makes' },
        { word: 'PAWS',     hint: "A cat's fluffy feet" },
        { word: 'HOME',     hint: 'Where Ollie wants to be' },
        { word: 'PURR',     hint: 'Happy sound cats make' },
        { word: 'FUZZY',    hint: 'Covered in soft fluffy fur' },
        { word: 'LOST',     hint: "When you can't find your way home" },
        { word: 'COZY',     hint: 'Warm and snuggly feeling' },
        { word: 'CUDDLE',   hint: 'Hold someone close and snuggle' },
        { word: 'RESCUE',   hint: 'Save someone who is in trouble' },
        { word: 'WHISKERS', hint: "Long stiff hairs on a cat's face" },
        { word: 'NUZZLE',   hint: 'Rub your nose against something warm and soft' },
        { word: 'SAFE',     hint: 'Protected and not in danger' },
        { word: 'BELONG',   hint: 'Be in the right place' },
        { word: 'RETURN',   hint: 'Come back to where you started' },
        { word: 'COMFORT',  hint: 'Make someone feel better' },
        { word: 'SUNBEAM',  hint: 'A warm stripe of sunlight from a window' },
        { word: 'CATNIP',   hint: 'A plant that cats go crazy for' },
        { word: 'PROWL',    hint: 'Walk quietly like a cat hunting' },
        { word: 'SNUGGLE',  hint: 'Curl up close to someone warm' },
        { word: 'TABBY',    hint: 'A striped cat with tiger markings' },
        { word: 'FLUFFY',   hint: 'Covered in soft fluffy fur' },
        { word: 'SHELTER',  hint: 'A safe place to stay' },
        { word: 'INDOOR',   hint: 'Inside the house where it is warm' },
        { word: 'BASKET',   hint: 'A cozy bed for a cat' },
        { word: 'GENTLE',   hint: 'Soft and kind and careful' },
        { word: 'PLAYFUL',  hint: 'Loves to play and have fun' },
        { word: 'MISSING',  hint: 'Gone and not where you expect' },
        { word: 'WANDER',   hint: 'Walk around without knowing where you are going' },
        { word: 'YARN',     hint: 'Colorful string that cats love to play with' },
      ],
    },
  },

  // ── 9. What a Doodle Do ──────────────────────────────────────────────────────
  'what-a-doodle-do': {
    wordSearch: {
      title: 'Wake Up Farm Words!',
      wordPool: [
        'ROOSTER','CROW','DAWN','FARM','HENS','CLUCK','EGGS','NEST','WAKE','SUNRISE',
        'MORNING','BARNYARD','PREEN','FEATHERS','STRUT','FLOCK','GRAIN','FEED','SCRATCH','PECKING',
        'WATTLE','PERCH','COOP','GOLDEN','SUNLIGHT','EARLY','CHIRP','TWITTER','SPARROW','WREN',
        'ROBIN','TRACTOR','HAYSTACK','PASTURE','WINDMILL','MEADOW','CROWING','HATCHING','STRAW','SEEDS',
        'LADDER','GOLDEN','ORCHARD','MISTY',
      ],
    },
    crossword: {
      title: 'Doodle-Do Crossword',
      wordPool: [
        { word: 'CROW',     clue: 'The loud sound a rooster makes at sunrise', emoji: '🐓' },
        { word: 'EGGS',     clue: 'Round things hens lay in the nest',         emoji: '🥚' },
        { word: 'HENS',     clue: "Female chickens — mothers of the eggs",     emoji: '🐔' },
        { word: 'DAWN',     clue: 'When the sun first peeks up in the morning',emoji: '🌅' },
        { word: 'NEST',     clue: 'A cozy bed made of straw and twigs',        emoji: '🪺' },
        { word: 'CLUCK',    clue: 'Sound a chicken makes',                     emoji: '🐔' },
        { word: 'FARM',     clue: 'Place where animals and crops are raised',  emoji: '🏡' },
        { word: 'FEED',     clue: 'Give food to the animals',                  emoji: '🌾' },
        { word: 'COOP',     clue: 'A small shelter where chickens sleep',      emoji: '🏚️' },
        { word: 'GRAIN',    clue: 'Tiny seeds chickens love to eat',           emoji: '🌾' },
        { word: 'PERCH',    clue: 'A bar where birds sit and sleep',           emoji: '🐦' },
        { word: 'STRUT',    clue: 'Walk proudly like a rooster',               emoji: '🐓' },
        { word: 'PREEN',    clue: 'When a bird cleans its feathers',           emoji: '🦢' },
        { word: 'CHIRP',    clue: 'A little tweet from a small bird',          emoji: '🐦' },
        { word: 'GOLDEN',   clue: 'Shiny like the morning sun',                emoji: '☀️' },
        { word: 'MORNING',  clue: 'The beginning part of the day',             emoji: '🌅' },
        { word: 'SUNRISE',  clue: 'When the sun comes up over the horizon',    emoji: '🌄' },
        { word: 'ROOSTER',  clue: 'The boy chicken who wakes everyone up',     emoji: '🐓' },
        { word: 'FEATHERS', clue: 'Soft coverings that keep birds warm',       emoji: '🪶' },
        { word: 'BARNYARD', clue: 'The area around the farm buildings',        emoji: '🏚️' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'doodle-do' },
    hiddenObjects: { title: 'Find the Farm Things!', scene: 'doodle-do' },
    memoryMatch: {
      pairPool: [
        '🐓','🌅','☀️','🌾','🥚','🎵','🐔','🌻','🪺','🌈',
        '🏡','🌄','🐦','🦆','🦉','🦚','🦜','🌿','🌊','🍃',
        '⭐','🌙','🎶','🔔','🌺','🌸','🌼','🌱','🏚️','🚜',
        '🌳','🌤️','🫙','🏕️','🌠',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'ROOSTER',  hint: 'The bird that crows at sunrise' },
        { word: 'DAWN',     hint: 'When the sun first peeks up' },
        { word: 'CROW',     hint: "The rooster's loud morning call" },
        { word: 'EGGS',     hint: 'Round things hens lay in the nest' },
        { word: 'WAKE',     hint: 'The opposite of sleep' },
        { word: 'CLUCK',    hint: 'Sound a chicken makes' },
        { word: 'FARM',     hint: 'Place with animals and crops' },
        { word: 'FEED',     hint: 'Give food to the animals' },
        { word: 'COOP',     hint: 'A small shelter where chickens sleep' },
        { word: 'GRAIN',    hint: 'Tiny seeds chickens love to eat' },
        { word: 'PERCH',    hint: 'A bar where birds sit and sleep' },
        { word: 'STRUT',    hint: 'Walk proudly like a rooster' },
        { word: 'PREEN',    hint: 'When a bird cleans its feathers' },
        { word: 'CHIRP',    hint: 'A little tweet from a small bird' },
        { word: 'GOLDEN',   hint: 'Shiny like the morning sun' },
        { word: 'MORNING',  hint: 'The beginning part of the day' },
        { word: 'SUNRISE',  hint: 'When the sun comes up' },
        { word: 'FEATHERS', hint: 'Soft coverings that keep birds warm' },
        { word: 'BARNYARD', hint: 'The area around the farm buildings' },
        { word: 'CROWING',  hint: 'When a rooster sings his morning song' },
        { word: 'HATCHING', hint: 'When a baby chick breaks out of its egg' },
        { word: 'STRAW',    hint: 'Dry yellow stalks in the barn' },
        { word: 'WATTLE',   hint: "The red wobbly bit under a rooster's chin" },
        { word: 'SCRATCH',  hint: 'What chickens do on the ground looking for food' },
        { word: 'TWITTER',  hint: 'A sound birds make like chirping' },
        { word: 'SPARROW',  hint: 'A small brown bird on the farm' },
        { word: 'TRACTOR',  hint: 'The big machine that helps on the farm' },
        { word: 'HAYSTACK', hint: 'A big pile of dried hay' },
        { word: 'PASTURE',  hint: 'A grassy field where animals graze' },
        { word: 'WINDMILL', hint: 'A tall spinning machine on the farm' },
      ],
    },
  },

  // ── 10. The Shut-In Button ───────────────────────────────────────────────────
  'the-shut-in-button': {
    wordSearch: {
      title: 'Magical Button Words!',
      wordPool: [
        'BUTTON','MAGIC','PRESS','WISH','GLOW','POWER','DANCE','CANDY','FLOAT','DREAM',
        'SPARKLE','ZOOM','WHOOSH','BOUNCE','TWIRL','SPIN','FLIP','ZAP','POP','KAZAM',
        'WONDER','FLYING','SOARING','SURPRISE','BRIGHT','SHINY','GOLDEN','RAINBOW','CONFETTI','TREASURE',
        'ENCHANT','WAND','POTION','FAIRY','WINGS','DRAGON','CASTLE','UNICORN','SIZZLE','DAZZLE',
        'GLIMMER','FANTASTIC','SHIMMER','SPARKLY',
      ],
    },
    crossword: {
      title: 'Button Crossword',
      wordPool: [
        { word: 'WISH',     clue: 'What you make when you press the button',        emoji: '✨' },
        { word: 'GLOW',     clue: 'The magic button shines and does this',          emoji: '💡' },
        { word: 'DANCE',    clue: 'Move your body to the music!',                   emoji: '💃' },
        { word: 'PRESS',    clue: 'What you do with your finger to the button',     emoji: '👆' },
        { word: 'MAGIC',    clue: 'How the button makes things happen',             emoji: '🪄' },
        { word: 'CANDY',    clue: 'Sweet treat that appears when you press',        emoji: '🍬' },
        { word: 'FLOAT',    clue: 'Rise up and drift through the air',             emoji: '🌤️' },
        { word: 'ZOOM',     clue: 'Move super fast like a rocket',                 emoji: '🚀' },
        { word: 'SPARKLE',  clue: 'Shine and twinkle with tiny lights',            emoji: '✨' },
        { word: 'WHOOSH',   clue: 'The sound of flying through the air fast',      emoji: '💨' },
        { word: 'BOUNCE',   clue: 'Jump up and down like a bouncy ball',           emoji: '⚽' },
        { word: 'POWER',    clue: 'The energy that makes the button work',         emoji: '⚡' },
        { word: 'WAND',     clue: 'A magical stick that grants wishes',            emoji: '🪄' },
        { word: 'POTION',   clue: 'A magical drink that does something special',   emoji: '🧪' },
        { word: 'ENCHANT',  clue: 'Put a spell on something to make it magical',   emoji: '✨' },
        { word: 'BUTTON',   clue: 'Push it and something amazing happens!',        emoji: '🔘' },
        { word: 'RAINBOW',  clue: 'Colorful arc that appears by magic',            emoji: '🌈' },
        { word: 'GOLDEN',   clue: 'Shiny yellow like the most precious treasure',  emoji: '⭐' },
        { word: 'CONFETTI', clue: 'Tiny colorful pieces that rain down at a party',emoji: '🎊' },
        { word: 'UNICORN',  clue: 'A magical horse with a sparkly horn',           emoji: '🦄' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'shut-in-button' },
    hiddenObjects: { title: 'Find the Magic Things!', scene: 'shut-in-button' },
    memoryMatch: {
      pairPool: [
        '🔘','✨','🎪','🍬','💃','🌈','🪄','💡','🚀','⚡',
        '🎇','🎊','🎉','🎠','🎡','🎢','🦄','🏰','🐉','🌟',
        '💝','🔮','🎭','🎨','🌀','💥','��️','⭐','🪩','🎵',
        '🎶','🌸','🍭','🎯','🎁',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'BUTTON',    hint: 'Push it and something magical happens' },
        { word: 'MAGIC',     hint: 'Wonderful and surprising things' },
        { word: 'WISH',      hint: 'What you make when you press the button' },
        { word: 'DANCE',     hint: 'Move your body to the music' },
        { word: 'GLOW',      hint: 'The button shines and does this' },
        { word: 'CANDY',     hint: 'Sweet treat that appears by magic' },
        { word: 'FLOAT',     hint: 'Rise up and drift through the air' },
        { word: 'ZOOM',      hint: 'Move super fast like a rocket' },
        { word: 'SPARKLE',   hint: 'Shine and twinkle with tiny lights' },
        { word: 'BOUNCE',    hint: 'Jump up and down like a bouncy ball' },
        { word: 'POWER',     hint: 'The energy that makes the button work' },
        { word: 'WAND',      hint: 'A magical stick that grants wishes' },
        { word: 'POTION',    hint: 'A magical drink that does something special' },
        { word: 'ENCHANT',   hint: 'Put a magic spell on something' },
        { word: 'RAINBOW',   hint: 'Colorful arc that appears by magic' },
        { word: 'CONFETTI',  hint: 'Tiny colorful pieces that rain down at a party' },
        { word: 'UNICORN',   hint: 'A magical horse with a sparkly horn' },
        { word: 'TWIRL',     hint: 'Spin around and around in a circle' },
        { word: 'WHOOSH',    hint: 'The sound of flying through the air' },
        { word: 'SOARING',   hint: 'Flying up high like a bird' },
        { word: 'SURPRISE',  hint: "Something you didn't expect" },
        { word: 'GOLDEN',    hint: 'Shiny yellow like precious treasure' },
        { word: 'DRAGON',    hint: 'A fire-breathing flying creature' },
        { word: 'CASTLE',    hint: 'A big magical palace' },
        { word: 'FAIRY',     hint: 'A tiny magical creature with wings' },
        { word: 'DAZZLE',    hint: 'Impress everyone with your brightness' },
        { word: 'SIZZLE',    hint: 'The sound of something exciting happening' },
        { word: 'GLIMMER',   hint: 'Shine with a soft flickering light' },
        { word: 'TREASURE',  hint: 'A wonderful collection of precious things' },
        { word: 'FANTASTIC', hint: 'Amazingly wonderful and exciting' },
      ],
    },
  },

  // ── 11. Frog-a-Dog ───────────────────────────────────────────────────────────
  'frog-a-dog': {
    wordSearch: {
      title: 'Pond Words!',
      wordPool: [
        'FROG','DOG','POND','BARK','CROAK','JUMP','SWIM','SLIME','FETCH','LILY',
        'SPLASH','WET','GREEN','LEAPING','HOPPING','PUPPY','WAGGLE','SNIFF','CHASE','MUDDY',
        'WEBBED','TADPOLE','STREAM','BOGGY','RIPPLE','CATTAIL','BULLFROG','PEBBLE','REEDS','WADING',
        'GULPING','ROLLING','PLAYFUL','BUBBLY','FISHY','MOSSY','WOBBLY','JUMPING','SWIMMING','CROAKING',
        'DRAGONFLY','LILY','SPLASHING','GIGGLY',
      ],
    },
    crossword: {
      title: 'Frog-a-Dog Crossword',
      wordPool: [
        { word: 'FROG',     clue: 'Green, jumpy, and loves lily pads',                       emoji: '🐸' },
        { word: 'POND',     clue: 'A small still body of water',                             emoji: '🌊' },
        { word: 'BARK',     clue: 'The loud sound a dog makes',                              emoji: '🐕' },
        { word: 'SWIM',     clue: 'How frogs move through water',                            emoji: '🏊' },
        { word: 'LILY',     clue: 'Beautiful flower that floats on the pond',                emoji: '🌸' },
        { word: 'CROAK',    clue: 'The sound a frog makes',                                  emoji: '🐸' },
        { word: 'JUMP',     clue: 'Leap up into the air',                                    emoji: '⬆️' },
        { word: 'FETCH',    clue: 'What dogs love to do with a stick',                       emoji: '🐕' },
        { word: 'SPLASH',   clue: 'What happens when you jump into water',                   emoji: '💦' },
        { word: 'PUPPY',    clue: 'A young baby dog',                                        emoji: '🐶' },
        { word: 'TADPOLE',  clue: 'A baby frog that swims like a fish',                      emoji: '🐸' },
        { word: 'MUDDY',    clue: 'Covered in wet dirt from the pond',                       emoji: '💩' },
        { word: 'RIPPLE',   clue: 'Tiny waves spreading out on water',                       emoji: '🌊' },
        { word: 'REEDS',    clue: 'Tall plants growing at the edge of the pond',             emoji: '🌿' },
        { word: 'WEBBED',   clue: 'Feet with skin between the toes for swimming',            emoji: '🐸' },
        { word: 'STREAM',   clue: 'A small flowing river',                                   emoji: '💧' },
        { word: 'PEBBLE',   clue: 'A small smooth round stone',                              emoji: '🪨' },
        { word: 'BULLFROG', clue: 'A very big loud frog',                                    emoji: '🐸' },
        { word: 'CATTAIL',  clue: 'A tall brown pond plant that looks like a hot dog',       emoji: '🌾' },
        { word: 'MOSSY',    clue: 'Covered in soft green moss near the pond',                emoji: '🌿' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'frog-a-dog' },
    hiddenObjects: { title: 'Find the Pond Things!', scene: 'frog-a-dog' },
    memoryMatch: {
      pairPool: [
        '🐸','🐕','🌿','💧','🌊','🐾','🌳','🐟','🦋','🌸',
        '🌺','🐝','🍃','🌱','��','🌾','🪨','🏞️','🌤️','☀️',
        '🌈','🐛','🦗','🐠','🐡','🦐','🦀','🐙','🎣','💦',
        '🌻','🌼','🏊','🐊','🦆',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'FROG',      hint: 'Green jumpy loves lily pads' },
        { word: 'POND',      hint: 'A small still body of water' },
        { word: 'JUMP',      hint: 'What frogs love to do' },
        { word: 'BARK',      hint: 'Loud sound a dog makes' },
        { word: 'SWIM',      hint: 'How frogs move through water' },
        { word: 'CROAK',     hint: 'Sound a frog makes' },
        { word: 'FETCH',     hint: 'What dogs love to do with a stick' },
        { word: 'SPLASH',    hint: 'What happens when you jump into water' },
        { word: 'PUPPY',     hint: 'A young baby dog' },
        { word: 'TADPOLE',   hint: 'A baby frog that swims like a fish' },
        { word: 'MUDDY',     hint: 'Covered in wet dirt from the pond' },
        { word: 'RIPPLE',    hint: 'Tiny waves spreading out on water' },
        { word: 'REEDS',     hint: 'Tall plants at the edge of the pond' },
        { word: 'WEBBED',    hint: 'Feet with skin between the toes for swimming' },
        { word: 'STREAM',    hint: 'A small flowing river' },
        { word: 'PEBBLE',    hint: 'A small smooth round stone' },
        { word: 'BULLFROG',  hint: 'A very big loud frog' },
        { word: 'CATTAIL',   hint: 'A tall brown pond plant' },
        { word: 'SLIME',     hint: 'Green gooey stuff that frogs are covered in' },
        { word: 'LEAPING',   hint: 'Jumping a really long way' },
        { word: 'HOPPING',   hint: 'Little jumps one after another' },
        { word: 'WAGGLE',    hint: 'Move side to side like a happy dog tail' },
        { word: 'WOBBLY',    hint: 'Shaky and not quite steady' },
        { word: 'BUBBLY',    hint: 'Full of bubbles like a frog pond' },
        { word: 'MOSSY',     hint: 'Covered in soft green moss' },
        { word: 'PLAYFUL',   hint: 'Loves to play and have fun' },
        { word: 'WADING',    hint: 'Walking slowly through shallow water' },
        { word: 'SNIFF',     hint: 'What a dog does with its nose' },
        { word: 'GREEN',     hint: 'The color of a frog' },
        { word: 'LILY',      hint: 'Beautiful flower that floats on the pond' },
      ],
    },
  },

  // ── 12. Brian the Ghost ──────────────────────────────────────────────────────
  'brian-the-ghost': {
    wordSearch: {
      title: 'Spooky Ghost Words!',
      wordPool: [
        'GHOST','BRIAN','WAVE','KIND','SPOOK','FLOAT','HAUNT','SMILE','SCARY','BOO',
        'FRIENDLY','MOAN','GROAN','CAPE','SHEET','HOLLOW','CREEP','SHADOW','ETHEREAL','PHANTOM',
        'SPIRIT','WISPY','DRIFTING','CHAINS','HOWL','SHIVER','TREMBLE','RATTLE','CASTLE','TOWER',
        'COBWEB','ATTIC','CRYPT','LANTERN','MIDNIGHT','CANDLE','WAIL','SCREAM','VANISH','APPEAR',
        'TWIST','SWIRL','INVISIBLE','MOONLIT',
      ],
    },
    crossword: {
      title: "Brian's Crossword",
      wordPool: [
        { word: 'WAVE',     clue: 'What friendly Brian does instead of scaring',    emoji: '👋' },
        { word: 'KIND',     clue: 'Brian is this — the opposite of mean',           emoji: '💜' },
        { word: 'SPOOK',    clue: 'What other ghosts try to do',                    emoji: '👻' },
        { word: 'FLOAT',    clue: "How ghosts move — feet never touch the ground",  emoji: '🌫️' },
        { word: 'CAPE',     clue: 'A flowing costume piece ghosts wear',            emoji: '🧣' },
        { word: 'SMILE',    clue: "Brian's favorite expression",                    emoji: '😊' },
        { word: 'BOO',      clue: 'What a ghost might say to scare you',            emoji: '👻' },
        { word: 'MOAN',     clue: 'A spooky groaning sound',                        emoji: '👻' },
        { word: 'HAUNT',    clue: 'To stay in a house as a ghost',                 emoji: '🏚️' },
        { word: 'CHAINS',   clue: 'Clanky things some ghosts drag around',          emoji: '⛓️' },
        { word: 'HOLLOW',   clue: 'Empty and echoey inside',                        emoji: '🔊' },
        { word: 'SPIRIT',   clue: 'Another name for a ghost',                       emoji: '👻' },
        { word: 'CASTLE',   clue: 'Where Brian the ghost likes to live',            emoji: '🏰' },
        { word: 'PHANTOM',  clue: 'A ghostly invisible figure',                     emoji: '👻' },
        { word: 'COBWEB',   clue: 'Dusty spider web in a haunted house',            emoji: '🕸️' },
        { word: 'CANDLE',   clue: 'A flickering light in a haunted house',          emoji: '🕯️' },
        { word: 'LANTERN',  clue: 'A glowing light that lights dark halls',         emoji: '🪔' },
        { word: 'MIDNIGHT', clue: 'When the clock strikes twelve at night',         emoji: '🕛' },
        { word: 'FRIENDLY', clue: 'Nice and kind — like Brian the ghost!',          emoji: '💜' },
        { word: 'VANISH',   clue: 'Disappear all at once — poof!',                  emoji: '✨' },
      ],
    },
    findDiff: { title: 'Spot the Differences!', scene: 'brian' },
    hiddenObjects: { title: 'Find the Spooky Things!', scene: 'brian' },
    memoryMatch: {
      pairPool: [
        '👻','💜','🏚️','🕯️','🌙','⛓️','🕷️','✨','🌑','🔮',
        '🌫️','🏰','🕸️','🦉','🌕','🪔','⭐','🌟','🌌','🌃',
        '🎭','👋','😊','🌈','💫','🎪','🌀','🦇','🧟','💀',
        '🌠','🌜','🌛','🏺','🔔',
      ],
    },
    unscramble: {
      wordPool: [
        { word: 'GHOST',    hint: 'A spooky floating spirit' },
        { word: 'BRIAN',    hint: "The friendly ghost's name" },
        { word: 'WAVE',     hint: 'What friendly Brian does instead of scaring' },
        { word: 'KIND',     hint: 'Opposite of mean' },
        { word: 'FLOAT',    hint: 'How ghosts move without touching the ground' },
        { word: 'SPOOK',    hint: 'Frighten or startle someone' },
        { word: 'HAUNT',    hint: 'Stay in a house as a ghost' },
        { word: 'SMILE',    hint: "Brian's favorite friendly expression" },
        { word: 'CAPE',     hint: 'A flowing cloak worn by a ghost' },
        { word: 'MOAN',     hint: 'A spooky groaning sound' },
        { word: 'CHAINS',   hint: 'Clanky things some ghosts drag around' },
        { word: 'SPIRIT',   hint: 'Another name for a ghost' },
        { word: 'CASTLE',   hint: 'A big stone building where Brian lives' },
        { word: 'PHANTOM',  hint: 'A ghostly invisible figure' },
        { word: 'COBWEB',   hint: 'Dusty spider web in a haunted house' },
        { word: 'CANDLE',   hint: 'A flickering light in a haunted house' },
        { word: 'LANTERN',  hint: 'A glowing light that lights dark halls' },
        { word: 'MIDNIGHT', hint: 'When the clock strikes twelve at night' },
        { word: 'FRIENDLY', hint: 'Nice and kind just like Brian' },
        { word: 'VANISH',   hint: 'Disappear all at once poof!' },
        { word: 'SHIVER',   hint: 'Shake because you are cold or scared' },
        { word: 'TREMBLE',  hint: 'Shake with fear or excitement' },
        { word: 'HOWL',     hint: 'A long loud spooky sound' },
        { word: 'SHADOW',   hint: 'A dark shape that follows you around' },
        { word: 'CREEP',    hint: 'Move slowly and quietly like a ghost' },
        { word: 'WISPY',    hint: 'Light and floaty like smoke' },
        { word: 'DRIFTING', hint: 'Floating slowly through the air' },
        { word: 'ETHEREAL', hint: 'Light and magical like a ghost' },
        { word: 'RATTLE',   hint: 'Make a noisy clattering sound' },
        { word: 'HOLLOW',   hint: 'Empty and echoey inside' },
      ],
    },
  },

};
